import { gameboardFactory } from "../scripts/gameboard";

test("small gameboard", () => {
  let myBoard = gameboardFactory(3);
  expect(myBoard.board).toEqual([
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("big gameboard", () => {
  let myBoard = gameboardFactory(10);
  expect(myBoard.board).toEqual([
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("place ship at specific start coordinates", () => {
  let myBoard = gameboardFactory(10);
  let ship = myBoard.createShip(4);
  if (myBoard.checkPlacement(ship, 5, 5, true)) {
    myBoard.placeShip(ship, 5, 5, true, myBoard.getShips().length);
  }
  expect(myBoard.board).toEqual([
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: 0, index: 0 },
      { name: 0, index: 1 },
      { name: 0, index: 2 },
      { name: 0, index: 3 },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("fail to place ship at specific start coordinates", () => {
  let myBoard = gameboardFactory(10);
  let ship = myBoard.createShip(4);
  if (myBoard.checkPlacement(ship, 5, 8, true)) {
    myBoard.placeShip(ship, 5, 8, true, myBoard.getShips().length);
  }
  expect(myBoard.board).toEqual([
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("succeed to place ship at specific start coordinates (vertical)", () => {
  let myBoard = gameboardFactory(10);
  let ship = myBoard.createShip(4);
  if (myBoard.checkPlacement(ship, 5, 8, false)) {
    myBoard.placeShip(ship, 5, 8, false, myBoard.getShips().length);
  }
  expect(myBoard.board).toEqual([
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: 0, index: 0 },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: 0, index: 1 },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: 0, index: 2 },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: 0, index: 3 },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("succeed to place small ship", () => {
  let myBoard = gameboardFactory(10);
  let ship = myBoard.createShip(2);
  if (myBoard.checkPlacement(ship, 0, 0, true)) {
    myBoard.placeShip(ship, 0, 0, true, myBoard.getShips().length);
  }
  expect(myBoard.board).toEqual([
    [
      { name: 0, index: 0 },
      { name: 0, index: 1 },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
    [
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
      { name: "water", index: undefined },
    ],
  ]);
});

test("missed shot", () => {
  let myBoard = gameboardFactory(10);
  expect(myBoard.recieveAttack(5, 5)).toBe(false);
});

test.only("landed shot", () => {
  let myBoard = gameboardFactory(10);
  let ship = myBoard.createShip(4);
  if (myBoard.checkPlacement(ship, 0, 0, true)) {
    myBoard.placeShip(ship, 0, 0, true, myBoard.getShips().length);
  }
  myBoard.recieveAttack(0, 0);
  expect(ship.getHits()).toBe(1);
});
